version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: backendframework
    ports:
      - "5432:5432"
    volumes:
      - pgdata_projectx:/var/lib/postgresql/data

volumes:
  pgdata_projectx: